version: '3'

services:

  frontend:
    container_name: frontend
    restart: always
    build: 
      context: ./view
      dockerfile: Dockerfile
    # volumes:
    #   - ./view/:/app
    #   - /app/node_modules
    ports:
      - 3000:80
    # command: yarn start --network-timeout 1000000

  oauth:
    container_name: oauth-service
    build:
      context: ./oauth
      dockerfile: Dockerfile
    volumes:
      - ./oauth:/oauth
      - /oauth/node_modules
    ports:
      - 3001:3001